/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sonicbase_common_WindowsTerminal */

#ifndef _Included_com_sonicbase_common_WindowsTerminal
#define _Included_com_sonicbase_common_WindowsTerminal
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sonicbase_common_WindowsTerminal
 * Method:    enableAnsi
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_sonicbase_common_WindowsTerminal_enableAnsi
  (JNIEnv *, jobject);

/*
 * Class:     com_sonicbase_common_WindowsTerminal
 * Method:    getConsoleSize
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_sonicbase_common_WindowsTerminal_getConsoleSize
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
