#!/bin/bash

export SEARCH_HOME=$1

if [ ${1:0:1} != "/" ]
then
  export SEARCH_HOME=$HOME/$SEARCH_HOME
fi

mkdir -p $SEARCH_HOME/tmp

export mac=`which sw_vers`
echo $mac
if [ "$mac" == '' ]; then
    cat /etc/*-release > $SEARCH_HOME/tmp/distribution
else
    sw_vers > $SEARCH_HOME/tmp/distribution
fi

