#!/bin/bash

export SEARCH_HOME=$(echo $SEARCH_HOME | sed 's/\/bin\/..//g')
echo "SH=$SEARCH_HOME"

if [ "$_XMX_" = "" ]
then
  export _XMX_=2000m
fi

export _GC_=$_GC_LOG_FILENAME_

if [ "$_GC_LOG_FILENAME_" == "" ]
then
  export _GC_="$SEARCH_HOME/logs/gc.log"
fi

java_opts="-server  -XX:NewRatio=2 -XX:SurvivorRatio=10 -XX:+UseG1GC -XX:MaxGCPauseMillis=150 -XX:-ResizePLAB -XX:ParallelGCThreads=4 -XX:ConcGCThreads=2 -XX:-OmitStackTraceInFastThrow"
java_opts="$java_opts -verbose:gc -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=3 -XX:GCLogFileSize=2m -Xloggc:$_GC_"

if [ "$_LOG4J_FILENAME_" = "" ]
then
  export _LOG4J_FILENAME_="out.log"
fi

if [ "$_ERROR_LOG4J_FILENAME_" = "" ]
then
  export _ERROR_LOG4J_FILENAME_="errors.log"
fi

if [ "$_CLIENT_ERROR_LOG4J_FILENAME_" = "" ]
then
  export _CLIENT_ERROR_LOG4J_FILENAME_="client-errors.log"
fi


java_opts="$java_opts  -Dlogfilename=$_LOG4J_FILENAME_ -DerrorLogfilename=$_ERROR_LOG4J_FILENAME_ -DclientErrorLogfilename=$_CLIENT_ERROR_LOG4J_FILENAME_"

echo $java_opts

#java_opts="$java_opts -showversion -server  -XX:+UseG1GC -verbose:gc -Xloggc:$_GC_"
java_opts="$java_opts -XX:+CMSClassUnloadingEnabled -XX:+PrintGCDetails  -XX:-UseLargePagesIndividualAllocation"
java_opts="$java_opts -XX:+HeapDumpOnOutOfMemoryError  -Djava.net.preferIPv4Stack=true"
java_opts="$java_opts -XX:+PrintGCDetails -XX:+PrintGCTimeStamps "
java_opts="$java_opts -XX:-OmitStackTraceInFastThrow -XX:-UseLoopPredicate"
java_opts="$java_opts -Xmx$_XMX_ -XX:MaxDirectMemorySize=2g "
#-XX:ReservedCodeCacheSize=32m
java_opts="$java_opts -Dfamilysearch.search.disable.foreign.node.registration -Dfamilysearch.search.disable.central.log "
if [ "$LOG4J_FILE" = "cli-log4j.xml" ]; then
java_opts="$java_opts -Dlog4j.configuration=cli-log4j.xml"
else
java_opts="$java_opts -Dlog4j.configuration=log4j.xml"
fi

export _JAVA_OPTS_=$java_opts

if [ "$_JMX_PORT_" != "" ]; then
  export _JAVA_OPTS_=$_JAVA_OPTS_' -Dcom.sun.management.jmxremote.port='$_JMX_PORT_
fi
echo "search_home=$SEARCH_HOME"
_SEARCH_CLASSPATH_=$SEARCH_HOME/target/:$SEARCH_HOME/config/
for f in $SEARCH_HOME/lib/*.jar; do
  _SEARCH_CLASSPATH_=$_SEARCH_CLASSPATH_:$f
done

LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$SEARCH_HOME/lib/linux64

if [ "$MODE" = "debug" ]; then

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH
echo java $_JAVA_OPTS_ $_SYS_PROPS_ -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005 -cp $_SEARCH_CLASSPATH_ "$@" >&2
java $_JAVA_OPTS_ $_SYS_PROPS_ -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005 -cp $_SEARCH_CLASSPATH_ "$@"

elif [ "$MODE" = "yprof" ]; then

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:~/yjp-linux/bin/linux-x86-64
echo java $_JAVA_OPTS_ $_SYS_PROPS_ -agentlib:yjpagent=port=9009,probe_disable=* -cp $_SEARCH_CLASSPATH_ "$@" >&2
java $_JAVA_OPTS_ $_SYS_PROPS_ -agentlib:yjpagent=port=9009,dir=$SEARCH_HOME,probe_disable=* -cp $_SEARCH_CLASSPATH_ "$@"

else

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH
echo java $_JAVA_OPTS_ $_SYS_PROPS_ -cp $_SEARCH_CLASSPATH_ "$@" >&2
pushd $SEARCH_HOME
echo $SEARCH_HOME
java $_JAVA_OPTS_ $_SYS_PROPS_ -classpath $_SEARCH_CLASSPATH_ "$@"
popd

fi

