#!/bin/bash
ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no $1 mkdir -p $2
rsync -rvlLt --delete -e 'ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no' bin $1:$2
rsync -rvlLt --delete -e 'ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no' config $1:$2
rsync -rvlLt --delete -e 'ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no' lib $1:$2
rsync -rvlLt --delete -e 'ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no' keys $1:$2
rsync -rvlLt --delete -e 'ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no' mgmt $1:$2

#--exclude 'logs' --exclude 'tmp' -e 'ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'