#!/bin/bash

export SEARCH_HOME=$1

if [ ${1:0:1} != "/" ]
then
  export SEARCH_HOME=$HOME/$SEARCH_HOME
fi

mkdir -p $SEARCH_HOME/tmp

export mac=`which sw_vers`
echo $mac
if [ "$mac" == '' ]; then
    top -b -n 1 > $SEARCH_HOME/tmp/top
else
    top -l 1 > $SEARCH_HOME/tmp/top
fi

