#!/bin/bash

export SONIC_BASE_HOME=$1

if [ ${1:0:1} != "/" ]
then
  export SONIC_BASE_HOME=$HOME/$SONIC_BASE_HOME
fi

mkdir -p $SONIC_BASE_HOME/tmp

export mac=`which sw_vers`
echo $mac
if [ "$mac" == '' ]; then
    cat /etc/*-release > $SONIC_BASE_HOME/tmp/distribution
else
    sw_vers > $SONIC_BASE_HOME/tmp/distribution
fi

