#!/bin/bash

export SONIC_BASE_HOME=$1

if [ ${1:0:1} != "/" ]
then
  export SONIC_BASE_HOME=$HOME/$SONIC_BASE_HOME
fi

mkdir -p $SONIC_BASE_HOME/tmp

ls -l $SONIC_BASE_HOME/lib > $SONIC_BASE_HOME/tmp/jars
