#!/bin/bash

export mac=`which sw_vers`
if [ "$mac" == '' ]; then

kill -9 `ps -aux | grep java | grep $3 | grep $5 | grep -v grep | awk '{print $2}'`

export val="not"
while true; do
if [ "$val" == "" ]; then
  break
fi
sleep 1
export val=`ps -aux | grep java | grep $3 | grep $5`
done

else

kill -9 `ps | grep java | grep $3 | grep $5 | grep -v grep | awk '{print $1}'`

export val="not"
while true; do
if [ "$val" == "" ]; then
  break
fi
sleep 1
export val=`ps | grep java | grep $3 | grep $5`
done

fi

