replicationFactor: 2
dataDirectory: $HOME/db-data
installDirectory: $WORKING_DIR
compressRecords: false
useUnsafe: true
maxJavaHeap: 20%
user: ubuntu
clientIsPrivate: false
backup:
  bucket: sonicbase-test-backup
  period: daily
  prefix: backups
  time: 23:00
  type: AWS
  maxBackupCount: 10
shards:
- shard:
    replicas:
    - replica:
        publicAddress: localhost
        privateAddress: localhost
        port: 9010
        httpPort: 8080
    - replica:
        publicAddress: localhost
        privateAddress: localhost
        port: 9060
        httpPort: 8081
- shard:
    replicas:
    - replica:
        publicAddress: localhost
        privateAddress: localhost
        port: 9110
        httpPort: 8082
    - replica:
        publicAddress: localhost
        privateAddress: localhost
        port: 9160
        httpPort: 8083
clients:
- client:
    publicAddress: localhost
    privateAddress: localhost
    port: 8090
