replicationFactor: 1
dataDirectory: $HOME/db-data
installDirectory: $WORKING_DIR
maxJavaHeap: 20%
user: ubuntu
defaultPort: 9010
defaultHttpPort: 8080
servers:
- server:
    address: localhost
clients:
- client:
    address: localhost
    port: 8090
