replicationFactor: 1
dataDirectory: $HOME/db/a
compressRecords: false
useUnsafe: true
maxJavaHeap: 20%
user: ubuntu
clientIsPrivate: false
backup:
  bucket: sonicbase-test-backup
  period: daily
  prefix: backups
  time: 23:00
  type: AWS
  maxBackupCount: 10
streams:
  processorThreadCount: 8
  publisherThreadCount: 32
  producers:
  - producer:
      className: com.sonicbase.streams.LocalProducer
      maxBatchSize: 200
shards:
- shard:
    replicas:
    - replica:
        address: localhost
        port: 9010
        httpPort: 7080
- shard:
    replicas:
    - replica:
        address: localhost
        port: 9060
        httpPort: 7090
clients:
- client:
    address: localhost
    port: 8090
