replicationFactor: 1
dataDirectory: $HOME/db-data
maxJavaHeap: 20%
user: ubuntu
defaultPort: 9010
defaultHttpPort: 8080
defaultControllerPort: 8081
servers:
- server:
    address: localhost
clients:
- client:
    address: localhost
    port: 8090
