replicationFactor: 1
dataDirectory: $WORKING_DIR/db-data
compressRecords: false
useUnsafe: true
maxJavaHeap: 20%
user: ubuntu
clientIsPrivate: false
backup:
  bucket: sonicbase-test-backup
  period: daily
  prefix: backups
  time: 23:00
  type: AWS
  maxBackupCount: 10
shards:
- shard:
    replicas:
    - replica:
        address: localhost
        port: 9010
        httpPort: 8080
clients:
- client:
    address: localhost
    port: 8090
