replicationFactor: 1
dataDirectory: $HOME/db/b
compressRecords: false
useUnsafe: true
maxJavaHeap: 20%
user: ubuntu
clientIsPrivate: false
backup:
  bucket: sonicbase-test-backup
  period: daily
  prefix: backups
  time: 23:00
  type: AWS
  maxBackupCount: 10
streams:
  processorThreadCount: 8
  publisherThreadCount: 32
  consumers:
  - consumer:
      className: com.sonicbase.streams.LocalConsumer
shards:
- shard:
    replicas:
    - replica:
        address: localhost
        port: 9110
        httpPort: 8080
- shard:
    replicas:
    - replica:
        address: localhost
        port: 9160
        httpPort: 8090
clients:
- client:
    address: localhost
    port: 8090
