replicationFactor: 1
dataDirectory: $WORKING_DIR/db-data
installDirectory: $WORKING_DIR
compressRecords: false
useUnsafe: true
maxJavaHeap: 20%
user: ubuntu
clientIsPrivate: false
defaultPort: 8999
defaultHttpPort: 8080
backup:
  bucket: sonicbase-test-backup
  period: daily
  prefix: backups
  time: 23:00
  type: AWS
  maxBackupCount: 10
servers:
- server:
    address: localhost
clients:
- client:
    publicAddress: localhost
    privateAddress: localhost
    port: 8090
